### ISSUE TITLE
Failed build?

### ISSUE THREAD

**Issue by scheung38** [kenych/dockerizing-jenkins#1]
Hi could you show why no file or directory for Maven?

java.io.FileNotFoundException: /var/jenkins_home/downloads/apache-maven-3.5.2-bin.tar.gz (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at hudson.FilePath.installIfNecessaryFrom(FilePath.java:777)
Caused: java.io.IOException: Failed to install file:/var/jenkins_home/downloads/apache-maven-3.5.2-bin.tar.gz to /var/jenkins_home/tools/hudson.tasks.Maven_MavenInstallation/maven3
	at hudson.FilePath.installIfNecessaryFrom(FilePath.java:856)
	at hudson.FilePath.installIfNecessaryFrom(FilePath.java:764)
	at hudson.tools.ZipExtractionInstaller.performInstallation(ZipExtractionInstaller.java:81)
	at hudson.tools.InstallerTranslator.getToolHome(InstallerTranslator.java:72)
	at hudson.tools.ToolLocationNodeProperty.getToolHome(ToolLocationNodeProperty.java:109)
	at hudson.tools.ToolInstallation.translateFor(ToolInstallation.java:206)
	at hudson.tasks.Maven$MavenInstallation.forNode(Maven.java:662)
	at hudson.tasks.Maven$MavenInstallation.forNode(Maven.java:491)
	at org.jenkinsci.plugins.workflow.steps.ToolStep$Execution.run(ToolStep.java:152)
	at org.jenkinsci.plugins.workflow.steps.ToolStep$Execution.run(ToolStep.java:133)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE

**Comment by espoelstra** [comment]
From the main page of Jenkins, select "Manage Jenkins", then "Global Tool Configuration", then go down to the "Maven" section and expand it by clicking "Maven installations".

Currently the version and path is hardcoded which is causing the failure, delete the "Zip installer" but leave the "Install Automatically" box checked. Click on "Add installer" and select "From Apache" and then select any of the 3.5.x series. Click Save and attempt to build again.
